config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :aliens do
    collection do
      get 'search'
    end
    resources :bookings, only: [:new, :create]
    end
    resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        post ':id/rating/:rating' => :rating, as: :rating
      end
    end
end

app/models/alien.rb
class Alien < ApplicationRecord
  attr_accessor :rating
  has_one_attached :photo
  belongs_to :user

  validates :name, :species, :planet, presence: true
  validates :name, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :alien
  validates :appointment_start_date, presence: true
  validates :appointment_end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/alien_controller.rb
class AlienController < ApplicationController
  def index
    @aliens = Alien.all
  end

  def search
    @aliens = Alien.where("name LIKE ?", "%#{params[:q]}%")
  end

  def new
    @alien = Alien.new
  end

  def create
    @alien = Alien.new(alien_params)
    @alien.user = current_user

    if @alien.save
      redirect_to @alien, notice: 'Alien was successfully created.'
    else
      render :new
    end
  end

  def edit
    @alien = Alien.find(params[:id])
  end

  def update
    if @alien.update_attributes(alien_params)
      redirect_to alien_path(@alien)
    else
      render action: :edit
    end
  end

  def show
    @alien = Alien.find(params[:id])
    @bookings = Booking.where("alien_id = ?", "'#{@alien.id}'")
    if @bookings.length > 0
      average = bookings.sum(&:rating) / bookings.length
      @alien.rating = average
    end
  end

  def destroy
    @alien.destroy
    redirect_to aliens_path, notice: 'Alien was destroyed.'
  end

  private

  def alien_params
    params.require(:alien).permit(:name, :species, :planet)
  end
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  def index
    @aliens = Alien.all
    @aliens.each do |alien|
      bookings = Booking.where("alien_id = ?", "#{alien.id}")
      if !bookings.nil? && bookings.size > 0
        average = bookings.sum(:rating) / bookings.length
        alien.rating = average
      end
    end
  end

  def search
    @aliens = Alien.where("name ILIKE ?", "%#{params[:q]}%")
    @aliens.each do |alien|
      bookings = Booking.where("alien_id = ?", "#{alien.id}")
      if !bookings.nil? && bookings.size > 0
        average = bookings.sum(:rating) / bookings.length
        alien.rating = average
      end
    end
  end

  def new
    @alien = Alien.new
  end

  def create
    @alien = Alien.new(alien_params)
    @alien.user = current_user
    if @alien.save
      redirect_to @alien, notice: 'Alien was successfully created.'
    else
      render :new
    end

  end

  def edit
    @alien = Alien.find(params[:id])
  end

  def update

    @alien = Alien.find(params[:id])
    if current_user == @alien.user
      if @alien.update_attributes(alien_params)
        redirect_to alien_path(@alien)
      else
        render action: :edit
      end
    else
      redirect_to alien_path(@alien), notice: 'Cannot edit alien'
    end
  end

  def show
    @alien = Alien.find(params[:id])
    @bookings = Booking.where("alien_id = ?", "#{@alien.id}")
    if !@bookings.nil? && @bookings.size > 0
      average = @bookings.sum(:rating) / @bookings.length
      @alien.rating = average
    end
  end

  def destroy
    @alien = Alien.find(params[:id])
    if current_user == @alien.user
      @alien.destroy
      redirect_to aliens_path, notice: 'Alien was destroyed.'
    else
      redirect_to aliens_path, notice: 'Cannot delete alien.'
    end
  end

  private

  def alien_params
    params.require(:alien).permit(:name, :species, :planet, :user, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :edit, :update, :destroy, :rating]
  before_action :authenticate_user!
  def new
    @booking = Booking.new
    @alien = Alien.find(params[:alien_id])
  end

  def index
    @bookings = Booking.all
  end

  def create
    @alien = Alien.find(params[:alien_id])

    #check for bookings
    existingBookings = Booking.where("alien_id = ?", params[:alien_id])

    canBook = true

    startDate = params[:booking][:appointment_start_date]
    endDate = params[:booking][:appointment_end_date]

    for booking in existingBookings do
      if startDate.between?(booking.appointment_start_date, booking.appointment_end_date) ||
        endDate.between?(booking.appointment_start_date, booking.appointment_end_date) ||
        (startDate < booking.appointment_start_date && endDate > booking.appointment_end_date)
        canBook = false
        break
      end
    end


    if canBook
      @booking = Booking.new(booking_params)
      @booking.alien = @alien
      @booking.user = current_user
      if @booking.save
        redirect_to booking_path(@booking)
      else
        redirect_to new_alien_booking_path(@alien)
      end
    else
      redirect_to new_alien_booking_path(@alien), notice: 'Alien is already booked'
    end
  end

  def show; end

  def edit; end

  def update
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render action: :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  def rating
    if current_user == @booking.user
      @booking.rating = params[:rating]
      @booking.save
      redirect_to booking_path(@booking)
    end
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:appointment_start_date, :appointment_end_date, :alien_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aliens/edit.html.erb
<div class="row mt-5">
  <div class="col-6 offset-3">
      <div class="mt-5 mb-5 form">
        <%= simple_form_for(@alien) do |f| %>
          <%= f.input :name %>
          <%= f.input :species %>
          <%= f.input :planet %>
          <%= f.input :photo, as: :file %>
          <%= f.submit %>
        <% end %>
      </div>
      <%= link_to "Back", alien_path(@alien.id), class:"form_link" %>
  </div>
</div>

app/views/aliens/index.html.erb
<div class="container-index">
  <div class= "cards">
    <% @aliens.each do |alien| %>
      <%= link_to alien_path(alien) do %>
        <div class="card">
          <h3>Name: <%= alien.name %></h3>
          <h3>Species: <%= alien.species %></h3>
          <h3>Planet of Origin: <%= alien.planet %></h3>
          <h3>Rating:
          <% alien.rating.to_i.times do  %>
          <span class="fas fa-star"></span>
          <% end %>
          <% (5 - alien.rating.to_i).times do  %>
            <span class="far fa-star"></span>
          <% end %>
        </h3>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= link_to "Create a new Alien?", new_alien_path, class:"form_link" %>

app/views/aliens/new.html.erb
<div class="row mt-5">
  <div class="col-6 offset-3">
      <div class="mt-5 mb-5 form">
        <%= simple_form_for(@alien) do |f| %>
          <%= f.input :name %>
          <%= f.input :species %>
          <%= f.input :planet %>
          <%= f.input :photo, as: :file %>
          <%= f.submit %>
      <% end %>
      </div>
    <%= link_to "List of our Aliens", aliens_path, class:"form_link" %>
  </div>
</div>

app/views/aliens/search.html.erb
<div class="container-search">
  <div class= "cards">
    <% @aliens.each do |alien| %>
      <div class="card">
        <h3>Name: </h3>
        <p><%= link_to alien.name, alien_path(alien.id) %></p>
        <h3>Species: </h3>
        <p><%= alien.species %></p>
        <h3>Planet of Origin: </h3>
        <p><%= alien.planet %></p>
        <h3>Rating:</h3>
        <p><% alien.rating.to_i.times do  %>
            <span class="fas fa-star"></span>
          <% end %>
          <% (5 - alien.rating.to_i).times do  %>
            <span class="far fa-star"></span>
          <% end %>
          </p>
      </div>
    <% end %>
    <div class= "create-card">
      <h3><%= link_to "Create a new Alien?", new_alien_path %></h3>
    </div>
  </div>
</div>

app/views/aliens/show.html.erb
<div class="container-show">

  <div class="row justify-content-center">
    <div class= "col-6">
      <div class="card-show">
        <ul class="list-inline">

        <li><h2><%= @alien.name %></h2></li>
        <li><h3><%= @alien.species %></h3></li>
        <li><h3> <%= @alien.planet %></h3></li>

          <li><% if @alien.photo.attached? %>
            <%= cl_image_tag @alien.photo.key, height: 300, width: 300, crop: :fill %>
            <% else %>
            <%= image_tag "alien.png", alt: "Placeholder image", height: 300, width: 300, crop: :fill  %>
            <% end %></li>

    <ul><p>Rating: <% @alien.rating.to_i.times do  %>
      <span class="fas fa-star"></span>
    <% end %>
    <% (5 - @alien.rating.to_i).times do  %>
      <span class="far fa-star"></span>
    <% end %>
    </p>
    </ul>

        </ul>

        <ul class ="list-crud ">
          <% if current_user.id == @alien.user_id %>

        <li><%= link_to "Remove Alien",

                  alien_path(@alien),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>

        <li><%= link_to "Edit", edit_alien_path(@alien) %></li>
        <% end %>
        <li><%= link_to "Book", new_alien_booking_path(@alien) %></li>

        </ul>

      </div>
      <div class ="d-flex justify-content-center">
        <%=  link_to "Back to Aliens", aliens_path %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="row mt-5">
  <div class="col-6 offset-3">
      <div class="mt-5 mb-5 form">
        <%= simple_form_for(@booking) do |f| %>
          <%= f.input :appointment_start_date, as: :date, html5: true %>
          <%= f.input :appointment_end_date, as: :date, html5: true %>
          <%= f.submit %>
        <% end %>
      </div>
      <%= link_to "Back", booking_path(@booking.id), class:"form_link" %>
   </div>
</div>      

app/views/bookings/index.html.erb
<div class="container-index">
  <div class= "booking-cards">
    <% @bookings.each do |booking| %>
      <%= link_to booking_path(booking) do %>
        <div class="booking-card">
          <h3><%= "Your booking for #{booking.alien.name}" %></h3>
          <h3><%= "Start date: #{booking.appointment_start_date.strftime("%d-%m-%Y")}" %></h3>
          <h3><%= "End date: #{booking.appointment_end_date.strftime("%d-%m-%Y")}" %></h3>
          <h3><%= "Created: #{booking.created_at.strftime("%d-%m-%Y")}" %></h3>
          <i class="clock far fa-clock"></i>

        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="row mt-5">
  <div class="col-6 offset-3">
      <div class="mt-5 mb-5 form">
        <%= simple_form_for [@alien, @booking] do |f| %>
          <%= f.input :appointment_start_date, as: :date, html5: true %>
          <%= f.input :appointment_end_date, as: :date, html5: true %>
          <%#= f.input :rating, collection: 1..5%>
          <%= f.submit %>
        <% end %>
      </div>
  </div>   
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1>Your Booking</h1>
  <div class="cards">
    <div class="card">
        <p>Start Date: <%= @booking.appointment_start_date %></p>

        <p>Your rating:</p>
        <p>
          <% @booking.rating.to_i.times do |i|  %>
            <%= link_to rating_bookings_path(@booking, i+1), method: :post do %>
              <span class="fas fa-star"></span>
            <% end %>
          <% end %>

          <% (5 - @booking.rating.to_i).times do |i| %>
            <%= link_to rating_bookings_path(@booking, i + 1 + @booking.rating), method: :post  do %>
              <span class="far fa-star"></span>
            <% end %>
          <% end %>
        </p>

         <%= link_to "Cancel booking", booking_path(@booking),
         method: :delete,
         data: { confirm: "Are you sure?" }%>
         <%= link_to "Edit", edit_booking_path(@booking) %>
    </div>
  </div>
</div>

<%= link_to "Back to Bookings", bookings_path, class:"form_link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aliens4u</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="d-flex flex-column min-vh-100">
      <%= render 'shared/navbar' %>
        <div class="flex-grow-1 py-3">
          <%= yield %>
        </div>
      <%= render 'shared/flashes' %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="homepage">
  <div class="title_and_searchbar">
    <div class="welcome_title">
      <h1>Aliens4U</h1>
      <h2>Aliens... like you've never known before</h2>
    </div>
      <%= form_with url: "/aliens/search", method: :get, local: true do |form| %>
      <%= form.text_field :q %>
      <%= form.submit 'Search' %>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="main-footer">
<div class="social-media">
        <a href="#" class="fab fa-facebook"></a>
        <a href="#" class="fab fa-twitter"></a>
        <a href="#" class="fab fa-linkedin"></a>
      </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <%= link_to "Aliens4U", root_path, class: "alien4u-nav" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
        </li>
        <li class="nav-item dropdown">
          <!-- add a way to change a users profile picture and have it display here -->
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", "#", class: "dropdown-item" %>
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "My Aliens", aliens_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link"%>
        </li>
      <% end %>
    </ul>
  </div>
</div>